apply plugin: 'org.springframework.boot'

description = 'lightning playground example application package'

dependencies {
    implementation "fr.acinq.secp256k1:secp256k1-kmp-jni-jvm:${rootProject.ext.acinqSecp256k1KmpVersion}"
    implementation "fr.acinq.bitcoin:bitcoin-kmp-jvm:${rootProject.ext.acinqBitcoinKmpVersion}"
    implementation "fr.acinq.lightning:lightning-kmp-core-jvm:${rootProject.ext.acinqLightningKmpVersion}"

    implementation "com.google.protobuf:protobuf-java-util:${rootProject.ext.protobufVersion}"

    implementation project(':bitcoin-regtest:bitcoin-regtest-starter')

    implementation project(':spring-testcontainer:spring-testcontainer-lnd-starter')
    implementation project(':lnd-grpc-client:lnd-grpc-client-starter')

    implementation project(':spring-testcontainer:spring-testcontainer-cln-starter')
    implementation project(':cln-grpc-client:cln-grpc-client-starter')

    implementation 'io.projectreactor:reactor-core'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${rootProject.ext.springdocOpenApiVersion}"

    implementation 'io.micrometer:micrometer-registry-prometheus'

    exampleTestImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}
