apply plugin: 'org.springframework.boot'

description = 'lightning playground example application package'

dependencies {
    implementation rootProject.libs.bundles.acinq.lightning

    implementation rootProject.libs.protobuf.java.util

    implementation project(':bitcoin-regtest:bitcoin-regtest-starter')

    implementation project(':spring-testcontainer:spring-testcontainer-lnd-starter')
    implementation project(':lnd-grpc-client:lnd-grpc-client-starter')

    implementation project(':spring-testcontainer:spring-testcontainer-cln-starter')
    implementation project(':cln-grpc-client:cln-grpc-client-starter')

    implementation 'io.projectreactor:reactor-core'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation rootProject.libs.springdoc.openapi.ui

    implementation 'io.micrometer:micrometer-registry-prometheus'

    exampleTestImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}
