plugins {
    id 'java'
}

description = 'bitcoin zeromq client package'

dependencies {
    api 'io.projectreactor:reactor-core'

    implementation rootProject.libs.guava
    implementation rootProject.libs.jeromq

    testImplementation project(':bitcoin-zeromq-client:bitcoin-zeromq-client-test')
    testImplementation project(':tbk-bitcoin-common:tbk-bitcoin-common-util')
}
