plugins {
    id 'java'
}

description = 'lnurl simple implementation package'

dependencies {
    api project(':incubator:lnurl-java:lnurl-core')

    implementation rootProject.libs.bundles.acinq.bitcoin
    implementation rootProject.libs.bundles.apache.httpclient

    testImplementation project(':incubator:lnurl-java:lnurl-test')
}
