# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

org.gradle.caching=true
# https://docs.gradle.org/current/userguide/configuration_cache_enabling.html
# disable with `--no-configuration-cache`
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
# Possible values are [fail, warn]
#org.gradle.configuration-cache.problems=fail
org.gradle.configuration-cache.read-only=false
org.gradle.configureondemand=true
org.gradle.daemon=true
# disable with `--no-parallel`
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.warning.mode=all

# Possible values are [strict, lenient, off]
org.gradle.dependency.verification=strict
org.gradle.dependency.verification.console=verbose
