apply plugin: 'com.google.protobuf'

sourceSets {
    main {
        proto {
            // In addition to the default 'src/main/proto'
            srcDir file('src/main/java')
        }
        java {
            srcDir layout.buildDirectory.dir('./generated/source/proto/main/java').get().asFile
            srcDir layout.buildDirectory.dir('./generated/source/proto/main/grpc').get().asFile
        }
    }
}
configurations.configureEach {
    resolutionStrategy {
        dependencySubstitution {
            substitute module("com.google.protobuf:protobuf-javalite") using module("com.google.protobuf:protobuf-java:${rootProject.libs.versions.protobuf.get()}")
        }
    }
}

dependencies {
    implementation rootProject.libs.bundles.protobuf
}

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:${rootProject.libs.versions.protoc.get()}" }

    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:${rootProject.libs.versions.grpc.get()}" }
    }

    generateProtoTasks {
        all()*.plugins { grpc {} }
    }
}
