org.tbk.xchange:
  enabled: true
  specifications:
    bitstampExchange:
      exchange-class: org.knowm.xchange.bitstamp.BitstampExchange
      exchange-specific-parameters:
        Use_Sandbox: true
