plugins {
    id 'java'
}

description = 'spring testcontainer tor starter'

dependencies {
    api rootProject.libs.spring.tor.http
    api rootProject.libs.testcontainers
    implementation project(':spring-testcontainer:spring-testcontainer-core')

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter'

    annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure-processor'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}