apply plugin: 'org.springframework.boot'
apply plugin: 'net.bytebuddy.byte-buddy-gradle-plugin'

description = 'lnurl-auth example application package'

byteBuddy {
    transformation {
        plugin = org.jmolecules.bytebuddy.JMoleculesPlugin.class
    }
}

dependencies {
    implementation project(':incubator:lnurl-java:lnurl-simple')
    testImplementation project(':incubator:lnurl-java:lnurl-test')

    implementation project(':incubator:spring-lnurl:spring-lnurl-auth-starter')
    implementation rootProject.libs.spring.boot.starter.tor

    implementation rootProject.libs.bundles.acinq.bitcoin

    implementation rootProject.libs.bundles.zxing
    implementation rootProject.libs.bundles.apache.httpclient

    implementation 'io.projectreactor:reactor-core'

    implementation 'org.flywaydb:flyway-core'
    implementation rootProject.libs.sqlite.jdbc
    implementation rootProject.libs.hibernate.community.dialects

    implementation 'org.jmolecules:jmolecules-ddd'
    implementation 'org.jmolecules:jmolecules-events'
    implementation 'org.jmolecules.integrations:jmolecules-jpa'
    implementation 'org.jmolecules.integrations:jmolecules-ddd-integration'
    implementation 'org.jmolecules.integrations:jmolecules-spring'
    implementation 'org.jmolecules.integrations:jmolecules-jackson'

    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'

    implementation 'org.springframework.session:spring-session-jdbc'

    implementation 'io.micrometer:micrometer-registry-prometheus'

    exampleTestImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    exampleTestImplementation 'org.springframework.boot:spring-boot-starter-restclient'
}
