plugins {
    id 'java'
}

description = 'cln grpc client autoconfigure package'

dependencies {

    compileOnly rootProject.libs.cln.grpcclient

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    compileOnly 'org.springframework.boot:spring-boot-starter-actuator'

    annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure-processor'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation rootProject.libs.cln.grpcclient

    // TODO: add actuator endpoints
    // integTestImplementation 'org.springframework.boot:spring-boot-starter-actuator'
}
