plugins {
    id 'java'
}

description = 'xchange starter package'

dependencies {
    api rootProject.libs.xchange.core
    api project(':spring-xchange:spring-xchange-autoconfigure')

    api rootProject.libs.bundles.xchange.exchanges

    implementation 'org.springframework.boot:spring-boot-starter'
}
