FROM ghcr.io/theborakompanioni/electrum-daemon:4.6.0@sha256:f55ed2e0c4c2e80e195caa4ba4ef256f57ac621487112eb9b3897a3ee4139ec9

COPY --chown=electrum:electrum ./regtest/wallets /home/electrum/.electrum/regtest/wallets
