FROM ghcr.io/theborakompanioni/electrum-daemon:4.6.1@sha256:39b74e348ac0644e6b2bb5d12ced3d98e96d6929cac8383b9c149aa1beb916ae

COPY --chown=electrum:electrum ./regtest/wallets /home/electrum/.electrum/regtest/wallets
