FROM osminogin/electrum-daemon:3.3.8

COPY --chown=electrum:electrum ./regtest/config /home/electrum/.electrum/regtest/config
COPY --chown=electrum:electrum ./regtest/wallets /home/electrum/.electrum/regtest/wallets
