plugins {
    id 'java'
}

description = 'bitcoin zeromq bitcoin-kmp package'

dependencies {
    api project(':bitcoin-zeromq-client:bitcoin-zeromq-client-core')
    api rootProject.libs.acinq.bitcoin.kmp

    testImplementation 'io.micrometer:micrometer-core'
    testImplementation project(':bitcoin-zeromq-client:bitcoin-zeromq-client-test')
}
