org.tbk.spring.testcontainer.tor:
  enabled: true
  hidden-services:
    http_hs:
      # the following entry will setup something similar to this:
      # HiddenServiceDir /var/lib/tor/hidden_services/http_hs/
      # HiddenServicePort 80 127.0.0.1:8080
      virtual-port: 80
      host-port: 8080
  environment:
    TOR_DATA: '/home/tor/.tor'
    TOR_PASSWORD: 'any'
    TOR_EXTRA_ARGS: |
      # no exits allowed
      ExitPolicy reject *:*
      ## If you enable the controlport, be sure to enable a authentication method
      CookieAuthentication 1