apply plugin: 'org.springframework.boot'

description = 'electrum gateway example application package'

dependencies {
    implementation project(':bitcoin-regtest:bitcoin-regtest-starter')

    implementation project(':spring-testcontainer:spring-testcontainer-core')
    implementation project(':spring-testcontainer:spring-testcontainer-electrumx-starter')
    implementation project(':spring-testcontainer:spring-testcontainer-electrum-daemon-starter')
    implementation project(':incubator:tbk-electrum-daemon-client:tbk-electrum-daemon-client-starter')
    implementation project(':spring-testcontainer:spring-testcontainer-tor-starter')

    implementation 'io.projectreactor:reactor-core'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-quartz'

    testImplementation project(':spring-testcontainer:spring-testcontainer-test')
}
