plugins {
    id 'java'
}

description = 'electrum daemon jsonrpc client package'

dependencies {
    api rootProject.libs.arteam.rpcclient
    api 'tools.jackson.core:jackson-databind'

    implementation rootProject.libs.bundles.apache.httpclient

    integTestImplementation project(':bitcoin-regtest:bitcoin-regtest-starter')
    integTestImplementation project(':spring-testcontainer:spring-testcontainer-bitcoind-starter')
    integTestImplementation project(':spring-testcontainer:spring-testcontainer-electrumx-starter')
    integTestImplementation project(':spring-testcontainer:spring-testcontainer-electrum-daemon-starter')

    integTestImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    integTestImplementation project(':spring-testcontainer:spring-testcontainer-core')
    integTestImplementation project(':spring-testcontainer:spring-testcontainer-test')
}
