
services:
  bitcoind_regtest:
    container_name: bitcoind_regtest
    image: polarlightning/bitcoind:30.0@sha256:6b15e7efb79995a18441806f509e40316428a901f1cdc5c54cd25b03ac513cb9
    restart: no
    command:
      -regtest=1
      -server=1
      -whitelist=0.0.0.0/0
      -txindex=1
      -debug=0
      -dns=0
      -dnsseed=0
      -networkactive=0
      -uacomment=tbkdevbitcoindregtest
      -printpriority=1
      -logtimemicros=1
      -rpcauth=regtest:169f6ba28badca1d912ac0defebc8ceb$$2550c68dfde8ca3b4892415fa8779b6ea656a44e7af1642332afa06c1979e014
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -zmqpubhashblock=tcp://0.0.0.0:28334
      -zmqpubhashtx=tcp://0.0.0.0:28335
    expose:
      - "18443"
      - "28332"
      - "28333"
      - "28334"
      - "28335"
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "28335:28335"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "-chain=regtest", "-getinfo" ]
      interval: 3s
      retries: 20

  electrumx_regtest:
    container_name: electrumx_regtest
    image: lukechilds/electrumx:v1.18.0@sha256:c7e630b2ab68545a43907724d9e8b80b105c253ee9794bfa0658ada031a0d22d
    restart: no
    depends_on:
      bitcoind_regtest:
        condition: service_healthy
    expose:
      - "50001"
      - "50002"
    ports:
      - "50001:50001"
      - "50002:50002"
    environment:
      # https://github.com/spesmilo/electrumx/blob/1.18.0/docs/environment.rst
      DAEMON_URL: http://regtest:regtest@bitcoind_regtest:18443
      COIN: Bitcoin
      NET: regtest
      PEER_DISCOVERY: 'self' # default=on
      PEER_ANNOUNCE: ''
      LOG_LEVEL: debug
      DB_ENGINE: leveldb
      MAX_SEND: 10000000 # max RPC message size: increase this to support addresses with large histories
      MAX_SESSIONS: 250 # default=1000
      COST_SOFT_LIMIT: 0 # default=1000
      COST_HARD_LIMIT: 0 # default=10000
      INITIAL_CONCURRENT: 100 # default=10
      REORG_LIMIT: 3 # default=200; in blocks
      # set daemon poll intervals to support tests
      # more info on https://github.com/spesmilo/electrumx/issues/309#issuecomment-3815878015 (last checked 2026-01-30)
      DAEMON_POLL_INTERVAL_BLOCKS: 100 # default=5000; in milliseconds
      DAEMON_POLL_INTERVAL_MEMPOOL: 100 # default=5000; in milliseconds
    healthcheck:
      test: [ "CMD", "electrumx_rpc", "getinfo" ]
      interval: 3s
      retries: 20

  electrumd_regtest:
    build: ./data/electrum/.
    container_name: electrumd_regtest
    restart: no
    depends_on:
      electrumx_regtest:
        condition: service_healthy
    environment:
      - ELECTRUM_NETWORK=regtest
      - ELECTRUM_RPCUSER=rpc-user
      - ELECTRUM_RPCPASSWORD=rpc-pwd
      - ELECTRUM_RPCPORT=7000
      - ELECTRUM_CONFIG_ONESERVER=true
      - ELECTRUM_CONFIG_SERVER=electrumx_regtest:50002:s
      - ELECTRUM_CONFIG_AUTO_CONNECT=false # must be disabled if "oneserver" := true
      - ELECTRUM_CONFIG_CONFIRMED_ONLY=false
      - ELECTRUM_CONFIG_LOG_TO_FILE=true
    expose:
      - "7000"
    ports:
      - "7000:7000"
    healthcheck:
      test: [ "CMD", "electrum", "--regtest", "getinfo" ]
      interval: 3s
      retries: 20
