name: Build
on:
  pull_request:
  push:
    branches:
      - master
      - devel

jobs:

  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

  build:
    needs: validation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version-file: [ '.sdkmanrc' ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version-file: ${{ matrix.java-version-file }}

      - name: Print Java Version
        run: java --version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/devel' }}

      - name: Lint Gradle File
        run: ./gradlew autoLintGradle --no-parallel

      - name: Build project
        run: ./gradlew build spotbugsMain -x test

      - name: Unit Test
        run: ./gradlew test

      - name: Integration Test
        run: ./gradlew integrationTest

      - name: Publish Candidate
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          contains(github.ref, '-rc.')
        run: ./gradlew --info --stacktrace -Prelease.useLastTag=true candidate

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: |
          startsWith(github.ref, 'refs/tags/v')
        with:
          name: Package
          path: ./**/build/libs/*.jar
