apply plugin: 'org.springframework.boot'

description = 'tor testcontainer example application package'

dependencies {
    implementation project(':spring-testcontainer:spring-testcontainer-tor-starter')

    implementation 'io.projectreactor:reactor-core'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}
